radian-software/straight.el

- straight.el
If `use-package` is never loaded, the `(with-eval-after-load 'use-package ...)` body never runs. To avoid this, I define the functions required by the compiled output of `use-package` unconditionally. The rest of the integration remains in the `(with-eval-after-load ...)` as before.
> Fix use-package integration when use-package is not loaded at runtime

- straight.el
> [#213] Don't overwrite existing info files

- Makefile
> Actually use straight.el on Travis CI

- straight.el
This is my attempt to fix #210.
> Warn user if building info documentation fails

- straight.el
I built Emacs from the latest git source recently and `make` fails
```
-*- mode: compilation; default-directory: "~/.emacs.d/straight/repos/straight.el/" -*-
Compilation started at Thu Feb  1 10:47:11
make -k 
==> elint: compile: straight.el
In toplevel form:
straight.el:329:53:Error: ‘if-let’ is an obsolete macro (as of 26.1); use ‘if-let*’ instead.
==> elint: compile: bootstrap.el
straight.el: ‘if-let’ is an obsolete macro (as of 26.1); use ‘if-let*’ instead.
straight.el: ‘if-let’ is an obsolete macro (as of 26.1); use ‘if-let*’ instead.
straight.el: ‘if-let’ is an obsolete macro (as of 26.1); use ‘if-let*’ instead.
straight.el: ‘when-let’ is an obsolete macro (as of 26.1); use ‘when-let*’ instead.
straight.el: ‘when-let’ is an obsolete macro (as of 26.1); use ‘when-let*’ instead. …
```
> Replace if-let and when-let with if-let* and when-let*

- README.md
- straight.el
> Automatically fast-forward and reattach head

- .gitignore
- bootstrap.el
- straight-x.el
- straight.el
For #103.
This provides a new  command `straight-x-fetch-all`, it calls `git fetch` within all repos asynchronously. The interface is still rough.
> Fetch multi repos asynchronously

- straight.el
Addresses #258. As I mentioned there, we could also do without `if-let*` and `when-let*`, but those are used much more extensively, so waiting for your opinion on that.
> Simplify backports

- straight.el
This is a quick fix for the windows newline issue, at least until a better solution could be found.
> Newline normalization hack for #276

- README.md
- straight-x.el
Dear @raxod502 ,
in reply to your comment in [this issue](https://github.com/raxod502/straight.el/issues/246#issuecomment-472702266) I would like to ask for inclusion of my temporary solution for package pinning. 
I have updated the code to work with the changes introduced by commit [c42edf91249a3610a872402082e977c61cf65dc9](https://github.com/raxod502/straight.el/commit/c42edf91249a3610a872402082e977c61cf65dc9) and written a short tutorial on how to use it. 
I hope the code's quality is good enough for inclusion. If you require any changes please let me know and I will try to take care of them.
> Add package pinning to straight-x.el.

- straight.el
See also issue #418 and pull request https://github.com/raxod502/straight.el/pull/396
----
#
> Cygwin is considered to be Unix

- straight.el
Specifically keep server.el from aborting our session whenever `server-goto-toplevel` is called.
Fixes #453
> Prevent other packages from aborting straight recursive edit session

- straight.el
Causes https://github.com/hlissner/doom-emacs/issues/3406
Fixes #537
> Ignore seq package from melpa

- README.md
> Fix typo: recpie -> recipe

- README.md
- straight.el
Add keyword for overriding recipe repository sources on a per-recipe
basis.
see: #93
> Specify :source in recipe

- README.md
- straight.el
Compliment to straight-use-package-pre-build-functions.
see: #541
> Add straight-use-package-post-build-functions

- straight.el
> Fix: Don't assign :local-repo for :type built-in recipes

- README.md
> emasc-devel -> emacs-devel

- straight.el
Call `straight-vc-git--fork-repo` (introduced in #571) with enough
information to compute fork repo in `straight--convert-recipe`.
I tried to simplify the logic for recipe inheritance in `straight--convert-recipe`, too.
Let me know what you think.
> Fix: compute :fork repo name

- straight.el
Previous behavior only inherited `:files`.
discussion: https://github.com/raxod502/straight.el/pull/535#pullrequestreview-496004231
> straight--convert-recipe: inherit straight--build-keywords

- straight.el
Build off the behavior introduced in:
2c0ec731e79bd24b1e505c6b3e9cbdbab2488a7b
By pretty printing individual forms we can control how the top-level of
the report form is presented and defer to `pp-to-string` for each form.
This should maximize use of vertical space and prevent run-on,
single-line forms.
> straight-bug-report: Improve report formatting

- straight.el
Provide a local variable binding, `straight-bug-report-args`, in the subprocess program.
This allows code in the :pre/:post-bootstrap program to make use of
other arguments passed to `straight-bug-report`. e.g.
```emacs-lisp
:user-dir "test"
:post-bootstrap
(message "user-dir: %S" (plist-get straight-bug-report-args :user-dir)))
```
> straight-bug-report: Allow introspection

- straight.el
If a user specifies a local repository, we do not want to attempt to
look up a forge username for it when there is no `:host`.
e.g.
```emacs-lisp
(straight-use-package
'( package
:host github
:type git
:repo "https://www.host.org/repos/repo.git"
:local-repo "repo"
:fork (:host nil :repo "/home/user/repos/repo/")))
```
Fixes: #592
> Fix: straight-host-usernames: Bypass when :host is nil

- straight.el
> straight-bug-report: check before deleting directory.

- straight.el
> [#607] Use reset, not checkout, in initial clone

- README.md
> Use backticks in Markdown

- straight.el
Prevent truncation of printed lisp forms.
> straight-bug-report: nil-bind print level/length limits

- straight.el
> straight--warn-call: scroll to end of process buffer on error

- straight.el
A recent change on the `native-comp` branch has meant that passing load flag `late` is equivalent to passing load flag `t`, which causes packages to be unconditionally loaded after they're compiled.  This leads to all sorts of problems as some Elisp packages will error instantly on load!
~~This patch simply removes the `load` flag which should give the desired behaviour.~~
Edit: After discussion with upstream, we've agreed on an API, this PR implements the necessary changes.
> Fixes for the latest native-compile-async API

- .circleci/config.yml
- README.md
- bootstrap.el
- install.el
- scripts/smoke-test.bash
- straight-x.el
- straight.el
> Drop 24.5 support 

- README.md
- straight.el
Backport of #543/#630
See #650
> [Backport] Compute remote default branch name

- README.md
- straight.el
> Rename :build to :pre-build

- straight.el
> Fix straight-use-recipes docstring

- straight.el
> straight-bug-report: fix docstring reference to user-emacs-directory

- straight.el
Now that we're compiling in a child process, we need to add a package's
dependencies to the load-path prior to compiling. Otherwise macro definitions
defined in a dependency may not be present at compile time and result
in runtime errors.
See: #684
<details><summary>Test Case</summary>
```emacs-lisp
:user-dir "build-compile-load-dependencies"
:pre-bootstrap 
(setq straight-repository-user "progfolio" straight-repository-branch "fix/build-compile-load-dependencies")
:post-bootstrap 
(straight-use-package 'alert)
(with-current-buffer straight-byte-compilation-buffer
(message
(buffer-string)))
(alert "TEST PASSED"))
```
</details>
- Test run at: `2021-01-24 00:17:19`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> fix/build-compile-load-dependencies, …
> straight--build-compile: add package dependencies to load path

- straight.el
Now that the `:no-build` keyword has been replaced by the expanded
semantics of the `:build` keyword (#662), we only want to filter
candidates for building that have an explicitly nil `:build` keyword.
Additionally, we now present the candidates in the order they appear in
the recipe cache.
> straight--select-packge: fix for-build filter, candidate order

- straight.el
Replace FOR-BUILD and INSTALLED arguments with a generic FILTER argument.
Introduce predicate functions to replace FOR-BUILD and INSTALLED logic.
Replace ad-hoc checks with straight--build-disabled-p where appropriate.
Example usage:
```emacs-lisp
;; No filter
(straight--select-package "No filter")
;;previously nil 'intsalled
(straight--select-package "for-build" #'straight--buildable-p)
;;previously 'installed
(straight--select-package "installed" #'straight--installed-p)
;;previously 'for-build 'installed
(straight--select-package "both" #'straight--installed-and-buildable-p)
```
> straight--select-package: Add generic candidate filter.

- straight.el
Prefer errors over warnings for command failure.
Previous behavior would allow package :pre/post-build to fail and be silently
ignored on restarts.
Now if a `:pre/post-build` error occurs the user is presented with the `*Warnings*` buffer (which details the error and the recipe in which it occurred) and, in the case of a shell command error, the `*straight-process-buffer*` on start.
> straight--run-build-commands: error on failed :pre/post-build command

- README.md
> Fix documentation formatting, code example

- straight.el
Instead of troubleshooting/depending on make across various operating
systems (e.g. Windows), we can generate Org's org-version.el using git
and elisp.
See: #707
> Avoid make in Org recipes.

- install.el
- straight.el
> install.el: Exclude cygwin from straight--windows-os-p

- straight.el
`straight--process-call`:
wrapper for call-process which returns a list with exitcode, stdout, stderr
`straight--process-with-result`:
anaphoric macro which provides common bindings for results returned
by `straight--process-call`
`straight--process-run`:
wrapper for `straight--process-call` which logs and warns. Logging and
warnings are controlled by the variables `straight-process-log` and
`straight-process-warn`. The default behavior is to log and not warn.
`straight--process-run-p`:
Predicate which runs process and returns t if it exited with 0.
`straight--process-output`:
Runs process and returns its output.
The output is trimmed if the `straight--process-trim` variable is non-nil (defaults to t).
Add command and error faces to `straight-process-buffer` logs.
> Refactor external process API

- straight.el
> Add suggestion to update recipe repos when recipe not found

- straight.el
> straight-prune-build-directory: message when pruning

- straight.el
> straight--build-native-compile: Ensure native compilation available

- straight.el
> straight-vc-git-default-clone-depth: Support single branch option

- straight.el
> Split org-contrib into its own pseudo package

- straight.el
Renamed upstream:
https://github.com/emacs-mirror/emacs/commit/8bc91a6a3f6cc84f549d24467832f67b3130201d
> Rname comp-deferred-compilation-deny-list

- straight.el
Since #662, we only hit straight--build-native-compile when the
native-compile build step is enabled. We were mistakenly adding
every package to the deny list after native compiling it.
The other case we need to mind is when a recipe specifies
:build (:not native-compile), but the value for
`native-comp-deferred-compilation' is non-nil (the default). We need
to add those packages to the deny list if they aren't present during
subsequent Emacs sessions. Otherwise the recipe is only respected when
it is initially built, and will be native compiled when loaded after
Emacs has been restarted.
This should also cover the case where a package's recipe has been changed and is rebuilt.
> Properly manage `native-comp-deferred-compilation-deny-list'

- README.md
> Update Org mode references

- straight.el
> straight-use-package: guard against void native-comp deny list

- straight.el
Because of the change in #714, we weren't triggering the recursive
full clone when a shallow clone failed. straight--process-run returned
the process result list (nonzero-exit-code etc...) instead of throwing
an error.
See: #777
> vc-git--clone-internal: properly recurse when shallow clone fails

- straight-x.el
- straight.el
Obsolete straight-x-clean-unused-repos
See: #49
> Add straight-remove-unused-repos

- straight.el
> Add straight-dependencies, straight-dependents

- README.md
- straight-x.el
- straight.el
> merge develop into master

- straight.el
> straight-dependents: Improve interactive message

- tests/test-straight.el
See: #634
This brings us a step closer, but we still have to integrate the unit tests into the CI eventually.
> Test defcustom default types

- straight.el
> straight--transaction-alist: fix docstring typo

- straight.el
https://list.orgmode.org/8735pz50bw.fsf@gnu.org/
Fixes: #847
> straight-recipes-org-elpa-retrieve: update repo address

- straight.el
We accounted for a tag-less repo in #849.
However, the Org repo should usually have tags.
So now we use the original method (via git) and fall back to the
solution in #849 if necessary. This is analogous to what Org does.
Note there is a slight difference in the output of the two methods.
For example, the fallback method (which reads the "Version" metadata
field in org.el) will currently result in an ORVERSION of "9.5,
while the git, tag-based version will result in "9.4.6".
I suspect the tag based version will be slightly more performant as
well.
> recipes-org-elpa-build: use tags when available

- README.md
> Document straight-base-dir and friends

- straight-ert-print-hack.el
- tests/straight-test.el
> tests: Formatting; declare ert functions in print hack

- straight.el
> Fix: Implement merge-from-remote/upstream for built-in vc backend

- straight.el
> straight-bug-report: Open test case details by default

- straight.el
Seems like my attempt at a funny caused a great deal of grief in #877, it's not used for anything important so might as well take it out.
> [#877] Be less funny

- README.md
- straight.el
Closes https://github.com/raxod502/straight.el/issues/844
> [#844] Support :type nil properly

- straight.el
> Remove alias for straight-package-neutering-mode

- straight.el
Should give more information on Windows now.
Fixes: #861
> straight-version: Account for simulated symlinks

- Makefile
> Remove checkindent from "lint" Make target.

- straight.el
It's safe to assume that if someone wants the repository off disk, they have no use for the build dir.
> straight-remove-unused-repos: Remove unused build dirs, too

- straight.el
> straight-get-recipe: don't offer used repos interactively

- straight.el
Fixes #766
If the following upstream patch lands, we may need to adjust this:
https://list.orgmode.org/87r1a7rm6d.fsf@gmail.com/T/#t
> Build Org info

- README.md
> Add el-get to straight-recipe-repositories references

- straight.el
I host a bunch of forks (and own packages) at another forge so I made this customizable in straight. ♥
> Add custom variables for additional forges

- bootstrap.el
- straight.el
> Add NonGNU ELPA support

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/PULL_REQUEST_TEMPLATE.md
migrate link in `bug_report.md`
> migrate bug_report link to radian software org

- straight.el
- tests/straight-test.el
> add support for sourcehut :fetcher

- straight.el
> straight-recipes-nongnu-elpa-retrieve: update package list format

- straight.el
Org mode has changed the way the orgversion.el is generated upstream.
https://git.savannah.gnu.org/cgit/emacs/org-mode.git/commit/?id=c29d3e997
We now match their output.
<details open><summary>Develop: Test Case</summary>
```emacs-lisp
:post-bootstrap 
(straight-use-package 'org)
(org-version 'here 'full 'message))
```
</details>
- Test run at: `2022-11-25 16:21:49`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> fix/org-version, fork/fix/org-version) bf6bab8 2022-11-25`
- emacs-version: `GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6)
of 2022-11-14`
<details><summary>Output</summary>
```emacs-lisp
Bootstrapping straight.el...
Bootstrapping straight.el...done
Looking for gnu-elpa-mirror recipe → Cloning …
```
> straight-recipes-org-elpa--build: fix orgversion generation

- straight.el
> straight-get-recipe: Offer all recipe candidates interactively

- straight.el
straight-recipes-nongnu-elpa-version: bump version
See: #1025
> straight-recipes-nongnu-elpa--translate: handle string :ignored-files

- .github/workflows/ci.yml
- LICENSE.md
- README.md
- bootstrap.el
- scripts/docker-install.bash
- straight-x.el
- straight.el
@raxod502 These commits all look safe enough to merge to master to me. Thoughts?
> Bump master to develop

- bootstrap.el
- straight.el
Adding enough logging to be able to debug https://github.com/radian-software/straight.el/issues/1079.
> Logging improvements

- tests/mocks/.emacs.d/straight/build/straight-mock-repo/straight-mock-repo.el
https://github.com/radian-software/straight.el/issues/1121
> [#1121] Change broken symlink

- README.md
https://github.com/radian-software/straight.el/issues/1157
> [#1157] Clarify :if and :when behavior

- straight.el
Resolves #1186, see the added comment for explanation.
> [#1186] Load build cache earlier

- README.md
> Troubleshooting guide for package rebuilds

- README.md
Answer some questions from https://github.com/radian-software/straight.el/issues/915.
> [#915] Document contributing to built-in packages

- straight.el
Implements https://github.com/radian-software/straight.el/issues/1200.
> Output to stderr in batch mode

- straight.el
Closes https://github.com/radian-software/straight.el/issues/1189
> Change default URLs for (non-)GNU ELPAs

- README.md
> Add comparison to Nix

- straight.el
Fix https://github.com/radian-software/straight.el/issues/1191.
> Tweak NonGNU ELPA recipes from MELPA

- straight.el
Make the recipes returned by some of the less-general recipe repositories automatically conform to conventions followed by user configuration. The customizable URLs will automatically change to SSH if you customize `straight-vc-git-default-protocol`, and the custom options are updated to show choices for that. Changing these variables also now correctly invalidates the relevant recipe caches, fixing a bug introduced when those variables became customizable. In addition, recipe repositories that returned recipes based on a user-provided URL now automatically check whether that URL (most likely not customized, in the common case) matches one of the registered `straight-hosts`, and if so, make use of that configuration style. This is an infrastructural improvement that will support …
> Use :host correctly in other recipe repos

- straight.el
It is assumed that snapshot packages have not changed in revision or contents since they were installed. They can be read as is without further processing.
> Allow straight-freeze-versions with snapshots

- straight.el
> Fix recent bug in built-in VC backend

- straight.el
Closes https://github.com/radian-software/straight.el/issues/377 by making it so that, by default, eager modification detection is skipped for packages after the first time they are registered in an Emacs session (but it is performed again when the init-file is reloaded). You can customize `straight-check-for-modifications` by removing the `only-once` symbol if you wish to retain the previous behavior. The `only-once` symbol only has effect if paired with `find-at-startup`; all other modification detection modes are unaffected.
> Only check modifications once per init

- straight.el
Also improve the docstrings. Close https://github.com/radian-software/straight.el/issues/1007
> Show also packages with no dependencies

- README.md
Solve point 3 for https://github.com/radian-software/straight.el/issues/383
> Bit more watchexec docs

- README.md
- straight.el
We had some stuff in here that was marked deprecated back in 2018...
> Remove deprecated features

- README.md
Get yo news, hot n fresh! Finally we have some new things to report.
> Update news section

- straight.el
https://github.com/radian-software/straight.el/issues/1036#issuecomment-3151294919
> Condition warning on package-enable-at-startup

- straight.el
Handles part of https://github.com/radian-software/straight.el/issues/1265
> Respect XDG in package.el warning
