- README.md
Address #131, also reword a slightly confusing clause.
> Reflect function name changes in README

- straight.el
1. In `straight--select-package` add a new parameter `repo-present` which filters recipes by whether they have an available repository.
2. User vc operations (e.g. `straight-pull-package`) have been modified to filter for package with available repositories when using `straight--select-package`.
3. Only map over recipes with available repos in `straight--map-repos`.
> Only attempt vc operations on packages with avaliable repos, fixes #110

- straight.el
I'm trying to figure out how `straight-use-package` / `straight--build-package` works with Edebug, but it can't step inside macros due to lacking the Edebug specs.
> Add Edebug specs

- .travis.yml
- straight.el
This is my attempt to fix #200, which is inspired by Melpa's [package-build--generate-info-files](https://github.com/melpa/package-build/blob/fc706968dc0bb60e06c5d21025a6ea82d3279e96/package-build.el#L792) function.
> [#220] Build info manual from source directory

- straight.el
Without the fix, straight-use-package returns nil for built-in packages, however, according to the docstring and realted comments, it should return non-nil instead.
> Fix return value of straight-use-package

- straight.el
according to the docs this functions should return non-NIL if the key is found
in the hash. the actual code is returning non-NIL if the key is absent from the
hash table.
this also fixes rebuilding modified packages since straight--checkhash was used
straight--package-might-be-modified-p
> negate the return value of straight--checkhash

- straight.el
Previously this resulted in an error because it expanded
to (straight-use-package '(pkg-a pkg-b)).
> Support :straight (pkg-a pkg-b) syntax in use-package

- README.md
- straight.el
`straight-pull-all` now feches first, before merging all.
I've removed the low-level git pull commands as they're functionally covered by fetch and merge, and keeping the VC interface as simple as possible seems like a good idea.
Addresses some of #103
> Refactor pull operations to use fetch and merge

- README.md
`el-get` allows to specify a git revision, a branch or a tag. For example:
```lisp
(setq el-get-sources
'((:name org-mode
:checkout "release_9.1.13")
(:name cider
:checkout "v0.17.0")
(:name clojure-mode
:checkout "5.8.1")
(:name bbdb
:checkout "c951e15cd01d")
(:name magit
:checkout "2.13.0")))
```
Note I may have misunderstood the point. As a long time el-get user, other points seem valid to me.
> el-get can also specify git revisions

- README.md
- straight.el
Actually symlinks are supported on windows; it's just a bit weird that you have
to assign permission to the user. This patch detects if the user has the ability
to create symlinks and then conditionally activates their usage in straight.
The rant about MS Windows would have to fall victim to this patch.
> Document symlink setup on MS Windows

- README.md
This new section was added after the section that mentions integration
with use-package as recommended in #313. I decided that instead of
having "Integration with use-package" and "Integration with other
packages" as two separate sections, one after the other, it would look
"cleaner" if I "promoted" "Integration with other packages", and
included "Integration with use-package" as a subsection of it
> docs: add section relevant to integration with hydra

- straight.el
The shell command to `git remote add fork` needs to happen in the
context of the package's repo, and previously this was happening in
`straight/repos`, which is usually the user's `.emacs.d` repo. The first
time it does this, it doesn't fail, since you can add the fork remote to
the repo; but the second time (for another recipe with a fork), it
finally fails because fork already exists as a remote. Both of these
executions are incorrect anyway, because it should be done in the cloned
repo of the package. Fortunately, fixing this is as easy as moving the
logic down, such that `default-directory` is set to `repo-dir`.
> Fix bug when cloning with :fork

- README.md
- install.el
- straight.el
This PR adds option for shallow clone (`--depth N`), only for packages whose versions are *not* locked.
- This PR resolves #2 *partially*.
- This PR is based on #284.
I was thinking whether to continue #284, but I decided to create a new PR because #284 is too old to merge today.
I really want an option for shallow clones, but, unfortunately, it is difficult to treat version locking as discussed in #2. So I implemented an option for shallow clones only for packages whose versions are not locked.
Of cource, I know this implementation is far from complete, but it is useful at least for me (and hopefully some of other people).
I welcome any kind of comments, including disagreement.
Note that, if you add nothing in your `init.el`, then this PR does nothing.
```elisp
;; Change the default …
```
> Add option for shallow clones (--depth N)

- install.el
- straight.el
>* [Windows Creators Update](https://blogs.windows.com/buildingapps/2016/12/02/symlinks-windows-10/) supports  symlink-creation without any special permission setup.
This is not entirely correct for `Emacs` implementation of `make-symbolic-link`.
It seems that when calling `CreateSymbolicLink`, `Emacs` needs to add a new flag `SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE` for symlink can be created unpriviledged in Developer mode.
I've created a mitigation by using `mklink` command which works independently from `Emacs` implementation and supported in Windows.
> Fix symlink unpriviledged in windows

- README.md
- straight.el
This PR is kinda a catch-all for the things that I found that were ... not ideal with thawing:
* #294 - freezing after thawing is not a no-op
* #66 - thawing leaves detached HEADs around
* #58 - thawing requires fetching beforehand
I think the attached change solves all of these in a fairly neat way,
and I hope you think so too (and that I didn't miss some subtle
interaction!).
`straight-vc-git-check-out-commit` now normalizes the local repo when checking out a commit.
`straight-thaw-versions` now:
* Tries to ensure that the commit that we're thawing to is present by checking it's there, and if not, fetching.
* Uses a new and revamped check-out-commit function that `resets --hard` instead of running `checkout`.
With this change, I managed to thaw and re-freeze the versions (with an …
> straight-thaw-versions ergonomics improvements: auto-fetch, no decapitation

- straight.el
Don't call the things on the `straight-use-package-pre-build-functions` hook unless we're actually going to do a build.
I use the pre-build-functions hook to call `autoconf/configure/make` for the vm package before the build happens and w/out this change it was happening on every startup.  With this change it only happens when necessary.
Closes #386
> Don't call pre-build functions unless building

- straight.el
When emacs (27 at least) is byte-compiling `case-fold-search` is `nil` and searches become case-sensitive.
Certain packages don't capitalize "Package-Requires" because package.el is case-insensitive. For example, [dired-subtree](https://github.com/Fuco1/dired-hacks/blob/master/dired-subtree.el) uses "Package-requires".
This causes some package with uncommon capitalization to not have their dependencies handled by straight.el inside `eval-when-compile`.
Set `case-fold-search` to `t` in the header parser to ensure it's always searched for case-insensitively.
> Ensure Package-Requires is case-insensitive

- straight.el
No need to set "(setq straight-use-symlinks t)".  Tested on a couple of systems with Cygwin installed.
> symlinks ARE useable OOTB on cygwin

- install.el
- straight-x.el
- straight.el
This is a simple implementation of a configurable base path based on #300. 
There's a couple other changes/hacks that I've mentioned in comments.
This should not break existing installations as there are no changes to `bootstrap.el`.
Related to #274.
> Implement configurable base path

- straight.el
Useful when package is not already installed.
----
#
> Add user-facing function to visit a package's website

- straight.el
Not sure what is straight.el's policy to support older magit versions...
```
‘magit-status-internal’ is an obsolete function (as of Magit 2.91.0);
use ‘magit-status-setup-buffer’ instead.
```
----
#
> Fix magit deprecation warning

- straight.el
This was only done for info files generated from texinfo files but
some packages provide pre generated info files. This makes sure the
latter are added into the main info directory menu.
> Generate dir file for pre generated info files

- README.md
- straight.el
`:host`, `:repo`, and `:files` are inherited from the default recipe. Also `:fork` will inherit its host from the upstream recipe. These can be overridden like any recipe component.
closes #116 
For example, we can do the following simplification
before:
```lisp
(package :host gitlab :repo "other-user/repo" 
:files ("lisp.el")
:fork (:host :gitlab :repo "my-user/repo"))
```
after:
```lisp
(package :fork "my-user/repo")
```
or 
```lisp
(package :fork (:repo "my-user/repo"))
```
before:
```lisp
(package :host gitlab :repo "user/repo" :local-repo "local")
```
after:
```lisp
(package :local-repo "local")
```
Let me know what you think. If you give the green light I will add some documentation to the main README.
> Allow recipes to inherit from defaults

- README.md
- straight.el
Not a full solution for #442, but makes the workaround on MacOS/BSD systems less invasive.
> Move "find" out to customizable variable. Re: #442

- straight.el
This is probably not the ideal solution, but it makes stuff work until someone come up with a better one
> Use the appropriate quote in Windows (#393)

- straight.el
Hello,
I use the same `.emacs.d` across different operating systems and emacs versions. With package.el, I was using customized elpa directories (like e.g. `elpa-windows-26.3`) to avoid conflicts, essentially downloading and compiling the packages as many times as I had environments.
With `straight` so far, I could get a satisfactory result using a custom directory of the form `straight-windows-26.3` in which `straight` itself was placed.
However, I came to realize that with the way `straight` separates repositories and builds, it could be made more efficient by just separating the `build` subfolders, not the whole `straight` folder. 
For example, if I want to apply modifications to a package, I would need to do it only once, not once per environment. And it would allow (I guess, I didn't …
> Custom build directory

- README.md
Remove references to Travis and replace them with CircleCI
Use https://circleci.com/docs/2.0/status-badges/ to update the Status Badge
> Travis Status Badge to CircleCI Status Badge

- straight.el
`insert-file-contents-literally` prevents Emacs from doing automatic line ending detection and assumes that all line endings are `\n`. This is not true for non-unix encodings such as windows (CRLF).
One way to fix this issue is try and make all the line ending regex more verbose to deal with carriage returns. This is how this was handled in #416. However I believe that the correct solution is to let Emacs automatically handle the line endings (which it is design to do). This avoids edge cases and extra complexity in the code.
The way this issue this was manifest for me was that straight was leaving the carriage returns (`^M`) on the packages names when I went to pull new packages. As you can imagine that was obviously leading to issues where the names were invalid.
> Fix issue with CRLF line endings

- README.md
- straight.el
This adds support for native compilation (aka. "gccemacs"), where
byte-compiled elisp is compiled to native code. Modules will be native
compiled when they are byte-compiled, unless `:no-native-compile` or
`straight-disable-native-compilation` are set.
Has no effect on emacs versions without the `native-compile` function.
Possibly addresses #492.
> Support native compilation of packages

- straight.el
Blocking until native compilation has completed is not necessary or
desirable for standard usage of `straight.el`, so has been removed.
This has the added benefit of reducing our exposure to the API of
`comp.el` while it's under active development.
Related to #511 
Related to #507
> Don't block for native compilation

- straight.el
This is necessary to prevent a clone error when we try to perform a
shallow clone, fail, and recurse with depth `full`.  The shallow clone
attempt leaves a non-empty repo-dir which git refuses to clobber.
> Ensure directory doesn't exist before full clone

- straight-x.el
`straight-x.el` was not changed in https://github.com/raxod502/straight.el/commit/3037bb3ed1b905f18d2d6bee904d6a6a6e89b2a3 and still contains the old lockfile version.
> straight-x.el: update lockfile version

- straight.el
Several packages (e.g. realgud [1]) expect `load-in-progress` variable
to be set to `t` when their autoloads are evaluated, but `straight`
fails to do so in `straight--activate-package-autoloads`, thus
breaking build of such packages. This patch addresses the issue by
explicitly setting `load-in-progress` to `t` in
`straight--activate-package-autoloads`.
[1] https://github.com/realgud/realgud/blob/24c02f07c4ae6610278da1f04a2479dc3d9b6bdf/realgud.el#L179
> Set load-in-progress to t when processing autoloads

- straight.el
`cl-destructuring-bind` can destructure a plist given a list of symbols.
Leveraging this simplifies the definition of `staright--with-plist`.
> straight--with-plist: use cl-destructuring-bind

- straight.el
Allow multiple bindings in variable spec.
Declare indentation.
if-let: allow multiple else forms.
Define macros with proper namespace and alias when needed.
This will make it easier to debug the macros without overriding
if/when-let when developing on Emacs versions that already have those macros
bound.
fixes: https://github.com/raxod502/straight.el/issues/556
> Fix if-let, when-let macro backports

- straight.el
Points user to resolution when local repo names are in conflict.
Fixes https://github.com/raxod502/straight.el/issues/500
> Generate better warning for conflicting local repo names

- straight.el
Normalize recipe lists which only have a name. e.g.
(use-package :straight (package))
see: https://github.com/raxod502/straight.el/pull/558#issuecomment-682262415
This change also provides a small optimization to avoid repeatedly checking the car of the arg.
> use-package integration: normalize recipe list with only name

- straight.el
Deferred compilation automatically compiles any `.elc` that is loaded, and is now enabled by default on native-comp builds of Emacs.  This patch makes the `:no-native-compile` keyword behave as expected by blacklisting the package from deferred compilation.
> Add no-native-compile packages to deferred-compilation-black-list

- straight.el
When `straight-vc-git-default-clone-depth` is set to an integer, the presence of the `--depth` option to `git clone` results in a `fetch` refspec which is limited to the branch fetched:
remote.origin.fetch=+refs/heads/master:refs/remotes/origin/master
(Incidentally, `git clone` does this even without the `--single-branch` option which `straight.el` passes in this case.)
The (minor) problem with this is that if the user of `straight.el` wants to contribute development of that package, and the package has a workflow which involves other branches (e.g. Orgmode incorporates the latest changes onto a `maint` branch), then a straight git fetch origin (or equivalent via magit or some other UI) will not fetch any other branches.
Arguably this is working as intended, but it does violate the …
> shallow clone limits fetch refspec to single branch

- README.md
- straight.el
Add support for default usernames per vc host.
Compute :fork repo name when given partial string or t.
See: #113
> Add straight-host-usernames; Allow partial :fork repo spec.

- README.md
- straight.el
Convenience command to update registered recipe repositories.
Adds better error message for missing recipe case in
straight-get-recipe.
See: #397
> Add straight-pull-recipe-repositories

- .github/ISSUE_TEMPLATE/bug_report.md
- README.md
- straight.el
straight-bug-report: macro that allows declaring reproducible bug
reports. Test code is run in a clean Emacs environment. Output is
formatted to be easily shared.
straight-version: return straight.el version info
See: #471
> Add straight-bug-report, straight-version

- straight.el
Call to `message` was missing a formatting spec, so output of `straight-version` in testing environment was not being printed.
> Fix: straight-bug-report: add missing format spec to message

- straight.el
Add `:user-dir` keyword to `straight-bug-report`.
This can be useful for creating a temporary test environment which
exists for more than one call to `straight-bug-report`.
I'm using this as a faux-docker right now to work on #72 
e.g.
```emacs-lisp
:preserve t
:raw t
:user-dir "straight-arbitrary-build-commands"
:pre-bootstrap
(setq straight-repository-user "progfolio")
(setq straight-repository-branch "feat/support-arbitrary-build-commands-72")
:post-bootstrap
(delete-directory (straight--build-dir) 'recursive)
(message "%S" (straight-use-package '(org-plus-contrib :post-build ("notify-send" "OK")))))
```
I can make some changes a the end of the `:post-bootstrap` key and re-evaluate to see the output.
> straight-bug-report: allow specifying user-dir

- straight.el
If subprocess error produces output, show it in minibuffer.
Switch to straight-process-buffer automatically.
See: #509
> Fix: Better subprocess error handling

- straight.el
`straight--process-get-output` uses `buffer-substring` to copy the
output of a process, which means that the text properties are copied
too. Most of the time, this is fine, as there are no text properties.
However, when using the [`ws-butler`] package, the `ws-butler-chg`
text property is present and copied. This means that, for example,
`straight-freeze-versions` produces a `default.el` file looking like
this:
```emacs-lisp
(("alert" . #("7046393272686c7a1a9b3e7f7b1d825d2e5250a6" 0 40 (ws-butler-chg chg)))
("anchored-transpose" . #("43b37bbc5dc0fe4b7b1b46c5e1d98553e9b527ae" 0 40 (ws-butler-chg chg)))
..)
```
while it should be:
```emacs-lisp
(("alert" . "7046393272686c7a1a9b3e7f7b1d825d2e5250a6")
("anchored-transpose" . "43b37bbc5dc0fe4b7b1b46c5e1d98553e9b527ae")
..)
```
Fix this by …
> Ignore text properties in straight--process-get-output

- straight.el
`pp` and `pp-to-string` do a fair job of pretty printing the report
form, but they do not make optimal use of vertical space and tend to
produce wide forms. Multiple KEY VAL pairs are printed on the same line.
`straight-bug-report--report-form` returns a string which makes better
use of vertical space.
Before (with `pp` or `pp-to-string`):
```emacs-lisp
(straight-bug-report :preserve t :raw nil :user-dir "pretty-print-test" :pre-bootstrap
(message "hi")
(message "two")
:post-bootstrap
(message "bye"))
```
After (with `straight-bug-report--report-form`):
```emacs-lisp
:preserve t
:raw nil
:user-dir "pretty-print-test"
:pre-bootstrap 
(message "hi")
(message "two")
:post-bootstrap 
(message "bye"))
```
> straight-bug-report: Improve report form formatting

- README.md
- straight.el
Fixes #92 
This PR allows specifying git protocol as part of a package recipe.  
I included the note about only using it for recipe overrides, because I couldn't think of another use case, correct me if I'm wrong (the only reason why I took this on is because I have all packages cloned over SSH, except for `org-drill`, which is on GitLab where I don't have an account, so I had to clone it over HTTPS).
Also, does it make sense to specify a different protocol for a fork? I haven't included this functionality because I don't use forks, but I don't think it would be hard to add it.
> Allow specifying protocol in package recipes

- straight.el
Simplify logic of case where `:fork` is a list.
This fixes a bug where the old logic would not return the correct `:repo` for `:fork` lists that don't explicitly specify the `:host` or `:repo`. e.g.
```emacs-lisp
'( package :type git :host github :repo "upstream/origin" :fork (:branch "feature"))
```
> Fix: straight-vc-git--fork-repo: cover case of :fork without :repo

- straight.el
`update-directory-autoloads` obsoleted as of:
https://github.com/emacs-mirror/emacs/commit/6f36b67e4146ef4610916b7903fd292e1308daf5
See: #601
> Add compatibilty for Emacs > 28.1 make-directory-autoloads

- straight.el
Rather than assume a default of "emacs", we can use the path of the
currently running Emacs session. This should prevent the user from
having to manually specify an :executable in most cases.
See: #599 user is on MacOS and "emacs" is was not the appropriate executable.
> straight-bug-report: programmaticly set executable default

- straight.el
As already seen in https://github.com/raxod502/straight.el/issues/287, on emacs 25 and earlier, delete-directory errors out if run on a non-existent directory.  So add more existence checks to prevent this.
> Add more existence checks for delete-directory

- Makefile
- tests/test-straight.el
Added a few unit tests using buttercup. They can be run with `make test` from the straight repo directory. They do assume buttercup is installed, so we'd have to arrange for that if we wanted to run these on CI, but that should be easy to do with straight itself.
Related: #478 #69 
Let me know what you think about this setup in general. If you like it, I'll try and get us covered on all the unit tests.
> Add unit tests

- straight.el
Otherwise striaght--vc--host-username does not recieve enough
information to compute the :repo string.
See: #612
> recipe conversion: use provided recipe for username lookup if  no default

- README.md
- straight.el
Command takes a recipe and executes it's :build commands.
See: #72, #389
> Add straight--run-build-commands

- tests/test-straight.el
I removed the top-level "describe" because it was redundant.
Reformatted things to make them a little easier to read as well.
Added tests for some utility functions.
I'll keep adding to this.
> unit tests: reformat; add more utiltiy function tests

- straight.el
If a shallow clone fails, the retried full clone will also fail because it's not passing the branch. Eg my local org-mode is pinned to 732aa477b031772c3694023cbf34eec6bdc08d61 ; a fresh clone results in this straight-process buffer:
```
$ cd /home/sjung/.config/emacs/straight/repos/org/
$ git init
Initialized empty Git repository in /home/sjung/.config/emacs/straight/repos/org/.git/
[Return code: 0]
$ cd /home/sjung/.config/emacs/straight/repos/org/
$ git remote add origin https\://code.orgmode.org/bzg/org-mode.git --master master
[Return code: 0]
$ cd /home/sjung/.config/emacs/straight/repos/org/
$ git fetch origin 732aa477b031772c3694023cbf34eec6bdc08d61 --depth 1 --no-tags
error: Server does not allow request for unadvertised object 732aa477b031772c3694023cbf34eec6bdc08d61
[Return …
```
> Include branch when shallow clone fails

- straight.el
Lexical binding is required for the sentinel function to work properly.
Rather than letting the subprocess launch and waste work, just throw a
user-error if straight-bug-report is executed without lexical binding
enabled.
> straight-bug-report: error when lexical binding nil

- straight.el
Prevents results buffer from stealing focus if user is doing something
else, e.g. typing while a longer running test is running.
> straight-bug-report: switch buffer on idle timer

- straight.el
A `:type` of `'(list ...)` fixes the number of elements, so anything other than a singleton list resulted in `(mismatch)` in the Custom buffer.  So change to `'(repeat ...)` to allow a variable number of symbols in the list.
> Fix defcustom for straight-check-for-modifications

- install.el
Due to the way handling Unicode on Windows, the evaluation of `straight.el` could fail in some cases. Adding comment `;; -*- coding: utf-8 -*-` will force the encoding, therefore could solve this problem.
> Fix installation issue on Windows

- bootstrap.el
- straight.el
Builds off #535 to add support for el-get recipes.
Closes: #115 
Related: #72
- only lists/retrieves recipes of `:type` `git` and `github`
This accounts for roughly 76% of el-get's packages. (1373 out of 1793)
- does not implement el-get's `:prepare` or `:post-init` behavior.
We breifly discussed this in #535, but I have some concerns about implementing it.
I'm not sure how to do this in a way that doesn't stomp `use-package` declarations and I think that sort of behavior is best left to `use-package` or similar solutions.
One idea I had was to simple report whether or not a package has a `:prepare` and/or `:post-init` value when installing the package. This way the user can add those commands to their init via their preferred method if they so choose.
- dependency management
I see that …
> Add el-get recipe support

- README.md
- straight.el
Add a hook so that users can automate custom configuration of elisp git repositories after they have been cloned.  For example, the `user.email` git config variable could be set on clone, to make upstream contributions more convenient for developers who use different email addresses for different repositories.
See https://github.com/aspiers/emacs/blob/3b2ec1b027065d360880984186ccd1ae419ecd4e/.emacs.d/init.d/as-package-loading.el#L133-L143 for an example.
----
> Add straight-vc-git-post-clone-hook for post-clone git config

- straight.el
Use (hopefully) locale independent regexp for parsing output of git command.
See: https://github.com/raxod502/straight.el/issues/646
> force locale for git remote branch look up

- straight.el
Org's `oldorg` make target overlaps with some of the work straight already does.
Byte compiling and generating autoloads twice is not only wasteful, but may cause errors (see: #624)
> Org recipes: prevent duplicate byte-compilation/autoloads

- README.md
Recommend setting package-enable-at-startup to nil in early-init.
Closes: #420, #663
> Document interaction of straight.el with early init-file

- straight.el
Work in progress using `make-process` to byte-compile packages in a child process.
Haven't dealt with the fact that we've made byte-compilation asynchronous.
For example, the :post-build commands should probably be executed in a callback after compilation.
> byte compile in child process

- Makefile
A small convenience. Defaults to running `clean lint`.
> Makefile: Add 'all' target

- straight.el
The org-version command depends on repository tags.
Using a shallow clone will cause this command (and others) to fail.
See:
https://orgmode.org/list/87y2h6yafs.fsf@kyleam.com/T/#t
https://github.com/raxod502/straight.el/issues/667
> Full clone Org in default recipes

- straight.el
Remove reference to `el-get-flatten` in the recursive branch of `straight--el-get-flatten` stub function.
-->
> straight--el-get-flatten: fix recursion

- README.md
- bootstrap.el
- straight.el
- tests/test-straight.el
An implementation of what I was suggesting with #659 and #655.
The README will need to be reworded, but I figured we could discuss the viability of such an approach before making substantial edits.
A recipe may specify build steps via the `:build` keyword.
(Note the original `:build` keyword has been renamed to `:pre-build`)
The `:build` keyword accepts the following values:
- `nil`
No build is executed. `:pre-build` and `:post-build` commands are not run.
```emacs-lisp
(example :build nil)
```
- `t`
Equivalent to running `straight--default-build-steps` (see below).
- `(step...)`
Each step in the list is a symbol which represents a function named `straight--build-SYMBOL`.
The function is passed the recipe as its sole argument.
Steps are executed in the order they are listed.
```emacs-lisp …
```
> Refactor/straight  build functions

- straight.el
Missed this in #535
Previously discussed here:
https://github.com/raxod502/straight.el/pull/535#discussion_r495020632
> Inherit :local-repo keyword

- README.md
- straight.el
Used to indicate one package is a superset of another. Originally mentioned in #352 and seems to have proliferated via copy+paste:
https://github.com/raxod502/straight.el/issues/624#issuecomment-729291385
https://github.com/syl20bnr/spacemacs/pull/14240
https://github.com/search?q=straight-use-package+org-plus-contrib+%3Aincludes&type=Code
> Add :includes keyword

- straight.el
If a package author adds more semi-colons to the package header line, we are dropping the package dependencies.
This is one of those cases where I'd consider it a bug in the author's package (though, it's more of a convention than anything technical), but also our bug because I can't think of a reason not to use a more forgiving regexp to find the `Package-Requires` line. Adjusted so any number of semi-colons at the start of the metadata are matched.
see: #682, https://github.com/zainab-ali/pair-tree.el/issues/1
>  straight--compute-dependencies: use more forgiving regexp

- straight.el
Users may set `straight-byte-compilation-buffer` to nil to ignore byte
compilation output. Attempting to `get-buffer-create` will fail in
this case.
> straight--build-compile: guard against nil byte-compilation-buffer

- straight.el
I use a proxy to accelerate git clone and fetch from Github for Doom Emacs,
straight.el always reports inconsistence between desired origin url of
`melpa/melpa.git` and actual remote origin url.  According to commands
below, it's obvious straight.el should use `git config --get` instead of
`git remote get-url`.
```
$ git config --global url.https://github.com.cnpmjs.org/.insteadOf https://github.com/
$ git config --get remote.origin.url
https://github.com/raxod502/straight.el
$ git remote get-url origin
https://github.com.cnpmjs.org/raxod502/straight.el
```
> correctly judge desired origin url when use GIT proxy

- straight.el
Previous logic assumed the FULL argument was nil when filtering directories.
> straight--directory-files: remove ".", "..", ".git" dirs when FULL paths

- straight.el
ox-odt looks for template-files in the etc/styles subdirectory. Including this and the styles files ensures correct behaviour. Previously, ox-odt found the styles-directory included with the org-version packaged with emacs (see the definition of org-odt-styles-dir-list).
> Include ox-odt styles when building org

- straight.el
See https://github.com/raxod502/selectrum/issues/437. I don't quite understand why it's so harmful to set `outline-regexp` in a file-local variable, but if Jonas says it's a bad idea, I trust him.
> [raxod502/selectrum#437] Use default outline-regexp

- straight.el
Prevents breakage due to globbing with different shells (e.g. ZSH).
See: #713
> straight-recipes-org-elpa--build: avoid shell-command-to-string

- README.md
> fix: README: remove reference to straight-install-package

- straight.el
This wasn't doing anything even before https://github.com/raxod502/straight.el/pull/715, which was probably the reason for https://github.com/raxod502/straight.el/issues/713 in the first place. The backslash needs to be doubled `\\` to be passed through to the actual shell. But now that we're not using a shell we don't need any escaping.
> [#715] Remove unnecessary backslash

- README.md
As we discussed in #505 I've added a bit more clarification about these keywords. I wasn't sure if the code snippets fit but I decided to just go with them anyways. Let me know if you'd prefer this PR not have them!
> Clarify usage for the git backend's :host and :repo keywords

- bootstrap.el
Works around #724, should effectively fix #697 and #643 as well (though most of that fix was upstream)
This allows Emacs to first attempt to load eln, then elc. It will fall back to el if neither exist, but the `byte-recompile-file` should eliminate that possibility.
Theoretically this is "slower" because it does a few more file existence checks based on `load-suffixes`, but in practice it's unlikely to be noticeable for one file and it eliminates the need to check for native compilation support and load that explicitly.
I still need to do a little looking into the file modification check to make sure it actually fixes #697 and #643
> Bootstrap attempts to load straight eln then elc

- install.el
- straight.el
If the user does not have git installed or it is not on the `exec-path` we can error sooner.
This should help us pinpoint those types of bugs sooner.
See #665
> Refuse to load if git executable not found.

- straight.el
This is generally recommended in the Elisp manual if I recall
correctly.
> Make message start with a capital letter

- straight.el
This is related to #630, but tackles a different issue regarding default branches: When cloning a repo at a specific commit, the repos isn't cloned but initiated and then the remote is added. That means if the default init branch (`init.defaultBranch` or `master`) isn't the same as the remote default branch, there's a branch mismatch. One might argue that it doesn't matter, as a specific commit is requested, however in practice it does: Emacs doom (using straight.el) fails on subsequent updates of a repo created like this (which may be a bug on its own). I believe using the remote default branch as proposed in this PR is a more sane/helpful starting point.
> Default branch when init on commit

- straight.el
Here's a small fix to the new magit-log feature. We need to set the `default-directory` around `magit-log-arguments` in addition to `magit-log-setup-buffer`.
> Fix magit-log-arguments working directory

- straight.el
Should be more performant and expresses intent more clearly.
> refactor: prefer mapconcat over string-join mapcar

- straight.el
Instead of checking during every recipe build for Emacs versions which do not have native compilation enabled, we can set this
variable's default value once.
> straight-disable-native-compile: Set default dynamcially

- straight.el
This is not going to change without a recompilation,
so it's safe to check it once and store the result in a variable.
> Don't check for native comp availability on every recipe build

- README.md
`org-plus-contrib` was removed from the README (#774) but replacing `org-plus-contrib` with `org-contrib` does not make sense in this case because org-contrib does not contain Org.
> Remove advice to load org-contrib as a means to load Org

- straight.el
git's init -b switch requires git version >= 2.28.
We can replicate this by renaming the master, which will work on older
git versions, too.
Use straight--process-run instead of straight--process-output, as we're
not doing anything with the process output.
See: https://github.com/raxod502/straight.el/issues/768
> vc-git--clone-internal: lower git version requirement; refactor

- straight.el
straight-makeinfo-executable: defcustom to set custom makeinfo path
straight-install-info-executable: defcustom to set custom install-info path
straight--executable-find: Wrapper for executable-find which allows us
to throw uniform errors if a required executable is not found on the exec-path.
> Add info program path customizations, straight--execuatable-find

- straight.el
I was able to reproduce both issues reported in https://github.com/raxod502/straight.el/issues/780 (modifications always detected, and text decoding errors), and with this change, neither occur anymore.
> [#780] Don't insert file contents literally

- straight.el
Hash recipe when creating transaction ID symbols. Unintern symbols
when transaction is complete. This keeps the symbol namespace clean
and prevents overly long symbol names from slowing down completion
frameworks, such as Company.
See: #803
> Refactor transaction recipe symbol IDs

- straight.el
Previous method involved looking up each package's dependencies.
It did not account for local-repo names and transitive dependencies.
Now we just recursively add straight's build dir to the load-path
when byte-compiling. This should cover all cases.
> straight--build-compile: properly set load-path

- straight.el
We don't use it in straight/build dir.
> straight--build-compile: Don't use local-repo

- straight.el
Function is not el-get specific and serves as a backward-compatible
version of `flatten-tree' for Emacs < 27.1.
> Rename straight--el-get-flatten to straight--flatten

- straight.el
- tests/test-straight.el
Function is only called during `straight-expand-files-directive`.
We can use `cl-pushnew` instead.
I believe this will be equivalent. Seem OK to you @raxod502?
> Remove straight--normalize-alist

- straight.el
Fixes hand-me-down bug I got for copying over Org's own make machinery.
Reported upstream with patch: https://orgmode.org/list/874kab2js1.fsf@gmail.com/#t
However, since we're bypassing Make altogether we can fix it
independent of upstream.
> straight-recipes-org-elpa--build: Fix orgversion string.

- straight.el
All operations are ignored.
We should not be trying to do any VC on :type built-in packages.
See: #875
> Add built-in pseudo VC backend

- straight.el
Similar to #780, if we insert-file-contents-literally, the text is not
properly encoded if it contains Unicode.
Fixes: #888
> straight--read-package-autoloads: Don't insert literally

- straight.el
Works better with `display-buffer-alist'.
> prefer `pop-to-buffer' over `switch-to-buffer-other-window'

- straight.el
Otherwise, a recipe with :type nil will throw an error when trying to get the local branch
since we may not be in a git repository.
> bug-report-package-info: Don't assume :type git

- straight.el
- tests/straight-test.el
generalizes straight--el-get-emacs to straight--emacs-path
See: #927
> org: Don't hard code Emacs path

- watcher/straight_watch_callback.py
Without this, I am getting modified files in the modified directory without a slash between parts: `nano-themenano-theme.el`, for example, rather than `nano-theme/nano-theme.el`. I am on `watchexec 1.18.6`.
> Watcher path concatenation is corrected

- straight.el
When non-nil, the left-margin variable may cause an extra opening
paren to be added to generated autoload files. This has been addressed
upstream in Emacs as of:
https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=fd5fe11211a469c42fb7142f5a26f577e8ff0010b
This patch prevents the problem in Emacs versions < 29.
See: #904
> straight--build-autoloads: Prevent spurious parens in autoloads

- straight.el
Removes session-specific temp file used to temporarily store
processes' stderr stream.
See: #939
> Add straight--delete-stderr-file

- straight.el
- tests/straight-test.el
Reduces info lookup/search time.
See: https://github.com/radian-software/straight.el/discussions/950
> straight--add-package-to-info-path: Only add dirs with "dir" file

- straight.el
Various packages have been adopted and moved out of org-contrib:
https://git.sr.ht/~bzg/org-contrib/refs/release_0.4
Also see #952.
> -recipes-org-elpa-retrieve: remove stale org-contrib :includes

- README.md
The readme mentioned that native-compilation is under development under the native-comp branch of emacs. However, this feature has already been merged into master and will be available in emacs 29 as far as I understand. However, even though it's merged, the `--with-native-compilation`  flag is disabled by default.
> Rephrase README that native-comp is now in emacs/master

- straight.el
This PR adds a interactive function to visit the local-repo of an installed package. I had this in my local config, which I find very helpful. Figured I'd add it here itself.
> Adding straight-visit-package-local-repo

- straight.el
Fixes issue #985.
I believe this may be what is needed, but I haven’t tested it extensively yet.
> Update for Emacs 29 where loaddefs-gen.el replaces autoloads.el

- straight.el
Allows visiting website for packages which are installed. Fixes #998
> straight-visit-package-website: include all recipes

- straight.el
Fix typo in the word "Pseudo" in the documentation string for `nil` and `built-in` functions.
> Fix typo in "Pseudo" for nil/built-in docstrings

- .github/workflows/ci.yml
cc @progfolio - trying to unbreak CI for https://github.com/radian-software/straight.el/pull/931. I've been doing this on other Emacs projects as well because I have found that testing against Emacs master introduces a lot of flakiness and generally imposes maintenance burden that doesn't seem to have a good return on investment given that we have limited resources.
In the medium-term future, I plan to make further changes to my Emacs projects to increase their maintainability and make it possible for me to do more active maintenance of all of them, including `straight.el`. I really appreciate that you already started effort in that direction by adding some tests. I should have done that in the first place, and I will likely add more in the future.
> Do not test against Emacs master

- straight.el
Emacs 29+ byte-compiler warns about unescaped single quotes.
> straight-use-version-specific-build-dir: fix docstring single quotes

- straight.el
See #1028
<details open><summary>Test Case</summary>
```emacs-lisp
:pre-bootstrap 
(setq straight-repository-user "progfolio" straight-repository-branch "fix/dependencies")
:post-bootstrap 
(straight-use-package 'epkg)
(message "epkg dependencies: %S"
(straight-dependencies "epkg")))
```
</details>
- Test run at: `2022-12-22 10:03:57`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> fix/dependencies, fork/fix/dependencies) 2882980 2022-12-22`
- emacs-version: `GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.35, cairo version 1.17.6)
of 2022-12-18`
<details><summary>Output</summary>
```emacs-lisp
Bootstrapping straight.el...
Bootstrapping straight.el...done
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for …
```
> straight--compute-dependencies: fix multiline metadata processing

- straight.el
Backwards compatibility so both the old and new formats work. See https://github.com/radian-software/straight.el/issues/1012, https://github.com/radian-software/straight.el/pull/1013.
This resolved `M-x straight-use-package` failing for me because I had an old checkout of NonGNU ELPA.
> Fix parsing of nongnu-elpa recipes

- straight.el
straight-use-package: FILTER out installed packages
See: #1024
> straight-get-recipe: change UNFILTERED to generic FILTER parameter

- straight.el
> [#1053] Handle renamed native-comp variable in Emacs 30

- scripts/docker-install.bash
This PR reduces the size of the CI docker image by skipping the installation of Debian recommended packages.
The output for "apt-get install" is now:
``` 
0 upgraded, 212 newly installed, 0 to remove and 1 not upgraded. Need to get 48.3 MB of archives.
```
instead of:
```
0 upgraded, 457 newly installed, 0 to remove and 1 not upgraded. Need to get 204 MB of archives.
```
> Reduce the size of the CI docker image

- README.md
I just found a little grammar typo while studying the `README.md`, which I fixed: `it's` instead of `its`.
> Typo: it's => its

- straight.el
The function `straight--process-call` was using `find-file-noselect` to read in the standard error after the process exits. This apparently runs a bunch of hooks and potentially turns on minor modes, which can be disruptive and slow. (Context of the particular issue I had is below.)
It seems like the recommended way to just read a file to a string is `with-temp-buffer` and `insert-file-contents`. See, for example, top answer to “[What's wrong with `find-file-noselect`?](https://emacs.stackexchange.com/a/2898/21511)” on stackexchange.
So I think this should be an invisible, work-alike improvement to an internal function.
Now, for my context: I'm using `undo-tree`, and by default, `undo-tree-auto-save-history` so that undo info is saved across killing and reopening the file or restarting …
> Use insert-file-contents when reading process stderr

- bootstrap.el
- straight.el
@progfolio We don't have good tools for responding to questions like https://github.com/radian-software/straight.el/issues/1079, where it's unclear whether there might be a bug, or just a configuration error, or some combination of the two. I've created a lightweight logging framework that can optionally produce additional diagnostic information about both Emacs initialization and user actions. We can add to it over time whenever we have a question we need answered by a reporter. This should assist in troubleshooting bug reports where the issue cannot be reproduced on our end (and even when reproduction is possible, it's usually slow/a pain).
What do you think?
> Add initial logging framework

- watcher/setup.py
- watcher/straight_watch.py
We also _really_ need to detect when the fs watcher is not working, and reinstall / alert the user. That is going to be my second highest priority probably, after adding better logging.
> Fix two issues that were breaking fs watcher

- straight.el
Fixes #1079
The convention of all the vc-git functions is that they return nil if they did something (which means we should double-check to make sure everything else is still as we expect, and register a repo modification).
Looks like the correct return value got lost in a refactor, understandable since I don't know that I documented this rather critical convention.
> Fix modification detection on merge

- README.md
- benchmark/straight-bench.el
- straight.el
Pretty self explanatory. If the user modifies `straight-base-dir` then of course they must modify the bootstrap snippet to use that directory instead of `user-emacs-directory`. However, we might as well do it automatically for them, instead of requiring this extra step.
> [#1120] Respect straight-base-dir in bootstrap

- install.el
To debug issues like https://github.com/radian-software/straight.el/issues/1118#issuecomment-1730532644 we need better logs when the bootstrap process failed. Just getting a truncated stacktrace that says the exit status was nonzero is rather useless. Let's additionally print a standard `message`, which won't get truncated.
I tested that when pointing the installation snippet at this branch, bootstrap still works. I also created a separate branch `rr-bootstrap-more-logs-testing` with the following diff on top of this PR:
```diff
diff --git a/install.el b/install.el
index f256479..5ed0051 100644
--- a/install.el
+++ b/install.el
@@ -260,7 +260,9 @@
emacs-binary-path))
nil '(t t) nil
"--batch" "--no-window-system" "--quick"
-                  "--load" temp-file)))
+ …
```
> [#1118] More logs on failed bootstrap

- straight.el
I think this is the right solution to https://github.com/radian-software/straight.el/issues/964 - per Jonas, the version of `seq.el` on GNU ELPA is newer than what is in Emacs now, and it is a legit package that people need to be able to install as a dependency. I'm not sure why this was in the list to begin with, maybe things were different in the past.
> [#964] Allow installing seq from GNU ELPA

- straight.el
This fixes a bug where recipes may contain symbols with positions, which have a printed representation but no read syntax, causing the subsequent load of the build cache to fail. Symbols with positions may be generated during the execution of the byte compiler.
The fix is to bind `print-symbols-bare` to `t` during the printing of the build cache in `straight--save-build-cache`. This strips the attached positions from the symbols. The attached positions are not used by `straight.el` in any way, so the build cache remains valid when loaded. The distinction between bare symbols and symbols with positions is only relevant here (during build cache save), since `symbols-with-pos-enabled` is bound to `t` during the execution of the byte compiler, causing symbols with positions to transparently …
> Set print-symbols-bare to t while saving the build cache

- Makefile
- straight.el
- tests/mocks/.emacs.d/straight/repos/melpa/recipes/bbdb
- tests/mocks/.emacs.d/straight/repos/melpa/recipes/ditz-mode
- tests/mocks/.emacs.d/straight/repos/melpa/recipes/git-link
- tests/mocks/.emacs.d/straight/repos/melpa/recipes/gitlab
- tests/straight-test.el
Close https://github.com/radian-software/straight.el/issues/1167. Remove the default behavior of renaming `.el.in` files in MELPA recipes as it has been removed upstream. Support `:rename` (which was added to upstream as a replacement) by translating it in the MELPA recipe fetcher into the cons-cell style renaming that was already supported in `straight.el`.
Add tests for the modified function, and mock data to support the tests. Change the indentation in the testing code to what Emacs wanted it to be by default, and add linting for the indentation in this file. (The changes are not entirely improvements, but if we want better indentation, we should make sure Emacs is configured to do it properly in this project rather than having it be a personal choice for each contributor.)
> [#1167] Support MELPA :rename

- straight.el
Compute child byte-compilation process load-path via straight-dependencies.
This should include the necessary transitive dependencies as well as
direct dependencies.
See: #1131
> straight--build-compile: fix compile process load-path

- install.el
Currently the bootstrap assumes that the lockfile path must be relative file relative to `straight-base-dir/striahgt/versions`,
however, some users might prefer to manage their lockfile in their version controlled dotfiles repo (`~/.config/emacs/straight/versions`), and manage the straight data under XDG spec, aka `~/.local/share/emacs/`.
This patch updates the bootstrap script so that the user's lockfile file path is an absolute path, it will be used
> feat: respect absolute path for straight-profiles for bootstrap install

- .github/workflows/ci.yml
- README.md
- scripts/smoke-test.bash
- straight.el
Closes #1184
Also changes CI so that it will stop at the first error, instead of running all tests regardless, which should make error messages easier to read. I re-ordered the steps so that it will likely surface the most useful error first before running less critical linters.
Also fixes a bug affecting Emacs 27 and below which was exposed by an unrelated upstream update to the package we were installing in the smoke test, where unknown major modes in file-local variables caused an error while generating autoloads.
> [#1184] Update docs for recipe repos list

- README.md
From my initial reading of the docs (as a relative straight.el newbie) I didn't realize that local-repo was meant for working with files on the local file system, I assumed that it was something that you would use with your own git repository server.
I hope that by being more specific about what a "local repository" is that it will be easier for others to understand how to use the option.
I hope my understanding of what `local-repo` does is good, if not then hopefully we can still improve the wording while remaining accurate.
> Improve local-repo docs

- straight.el
It really bothers me when code doesn't indent properly by default. Make it easy for everyone.
> Add convenience indent for use-package fns

- bootstrap.el
- straight.el
Handle https://github.com/radian-software/straight.el/issues/619 comprehensively. Looking at these recipe repos, I feel some improvements could be made... but that is a separate issue.
The implementation should be fully backwards-compatible. Unless you are running a forked version of `straight.el` that adds custom external dependencies tracked in a default recipe repository(?!). I don't think anyone in the world has done that.
> Allow customizing default recipe repositories

- straight.el
Lambdas can turn into compiled-bytecode when `straight.el` is byte-compiled, making the code for checking that the argument is a lambda no longer work. The objective was to avoid symbols being accidentally interpreted as functions, so change the implementation to check that more explicitly.
> Log Git commit correctly

- install.el
- straight-x.el
- straight.el
Now we get:
```
Debugger entered--Lisp error: (error "straight.el bootstrap failed, see *Messages*")
```
And in `*Messages*`:
```
Bootstrapping straight.el...
straight.el bootstrap failed with status 255, subprocess logs follow:
------2025-06-10 14:26:27.113 <modification-detection>: Loading build cache
2025-06-10 14:26:27.116 <vc>: Invoking VC method clone of type git with args: ((:type git :host github :repo "radian-software/straight.el" :branch "wip/bootstrap-logging" :package "straight\
" :local-repo "straight.el") nil)
2025-06-10 14:26:27.665 <process>: Got return status 128 from command: ("git" "clone" "--origin" "origin" "--no-checkout" "git@github.com:radian-software/straight.el.git" "/home/raxod502/fi\
les/temp/issue1063/straight/repos/straight.el/" "--no-single-branch" …
```
> Provide useful logs after failed bootstrap

- bootstrap.el
Re-loading the init-file would get you a warning about the recipe for el-get being redefined, which turned out to be because recipe inheritance was enabled, so the recipe for `straight.el` itself was trying to be looked up in existing recipe repos, which were still defined from last init, but not with their recipes, only the symbols, so the recipe repo recipes themselves were being looked up, and it turns out el-get had a recipe for el-get inside it, which was different from the one listed in `straight.el`. Hilarious!
> Fix ordering issue with el-get bootstrap

- straight.el
In some cases (errors, partial installs, deferred installs) it may be desired to `M-x straight-use-package` on a package that's already registered in the cache. Don't prevent doing so.
> Allow M-x straight-use-package already installed

- straight.el
Address issue discussed in https://github.com/radian-software/straight.el/pull/1207#issuecomment-2973142037. This caused `straight.el` to fail to determine the default branch of a repository when running `git remote show` required entering authentication credentials with `straight-display-subprocess-prompts` non-nil.
> Parse default branch more robustly

- straight.el
Only wipe the autoloads cache after an actual build, not unconditionally, as doing the latter will result in the autoloads cache not actually being used when it can be.
> Clear autoloads cache only on actual build

- straight.el
Fixes issues with Git hanging in various places when enabling the new interactive subprocess code.
> Disable Git pager in various places

- install.el
If `bootstrap-version` was not dynamically bound, then this code path would get triggered. Since that is rare, I guess nobody noticed that this variable was not actually defined as it was bound lexically and thus not propagated to the child Emacs process.
> Fix bad quoting in install script

- straight.el
You can specify :symlink t or :symlink nil in a recipe to override the global value of `straight-use-symlinks`. Close #1061
> New :symlink keyword for recipes

- straight.el
Fix #999. I elected to just remove the error-return case, and have errors be thrown directly. This seems more direct. And I know it will not be disruptive, because due to #999, the error-return case was causing an error to be thrown by the error-handling function anyway.
> Handle errors correctly for process invocations

- straight.el
Implement #149. Customize the new user option `(setq straight-vc-use-snapshot-installation t)` to have new Git clones use snapshot installation instead. When this is enabled, a repository clone is replaced instead by a download+extraction of a tarball from the VC host at the same commit, with a tracking file named `.straight-commit` noting the commit that was downloaded. Alist `straight-hosts` is extended with the ability to specify the schema for such tarball URLs. Passing a prefix argument to `M-x straight-normalize-package` will install version-history into the existing package snapshot, and then prompt you if there are any unexpected differences from the commit that the snapshot was supposed to represent, for example if local changes had been made after installation. When visiting an …
> Snapshot installation: optimize package downloads

- README.md
I think the information requested in https://github.com/radian-software/straight.el/issues/1078 is already present in the documentation; it just isn't located in the `use-package` section, because it's not specific to `use-package`; rather, the `use-package` integration simply allows you to use any recipe keywords supported by `straight.el`. Accordingly, I've added a cross-link to that section.
Please let me know what else is missing, and I will augment the documentation.
> Add cross-link to recipe format section

- README.md
- straight.el
Also disable the recipe lookup cache during interactive usage, for reasons explained in the new docs and added comment.
I think this addresses the issues raised in #1024, when combined with #1210 to allow re-loading existing packages.
> Add a section on troubleshooting caches

- README.md
- install.el
- straight.el
I was holding off on this for a long time because it seemed like it was going to break everything to change the default branch name, even though I already did so years ago on all my other hundred repositories, but now that I actually look at it, this should be a trivial change and shouldn't affect anyone's existing configurations of `straight.el`. Feel free to report any breakage and I can add further bridge code to assist in avoiding impact.
> Rename 'master' to 'main'

- straight.el
Fix: Update git submodules during package upgrades
Fixes #238
Straight.el runs `git submodule update --init --recursive` during initial clone but doesn't update submodules during package upgrades. When upstream repositories update submodule pointers, local submodules remain at old commits, causing repositories to appear dirty.
This addresses issue #238. Related issues include #502 and external reports like kaushalmodi/ox-hugo#346 where users encounter persistent submodule conflicts during upgrades.
The `gptel` package uses a test submodule. After upstream updates the submodule pointer, doom upgrade prompts:
```
> Repository "gptel" has a dirty worktree:
M test
1) Abort
2) Stash changes  
3) Discard changes
```
Add `git submodule update --init --recursive` after merges in …
> Fix: Update git submodules during package upgrades

- straight.el
Automatically detect NonGNU ELPA recipes in MELPA, and tweak them to respect the user's configuration for which NonGNU ELPA repository to use, which defaults to a more performant mirror than upstream. Also set the shallow clone configuration to one that is suitable for the NonGNU ELPA repository.
Closes https://github.com/radian-software/straight.el/issues/1259
> Improve NonGNU ELPA recipes from MELPA further
